In [1]:
import tensorflow as tf 

In [2]:
tenser = tf.constant([[1,2],[3,4]])

In [3]:
tenser

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [4]:
tenser.numpy()

array([[1, 2],
       [3, 4]], dtype=int32)

In [7]:
tenser = tf.Variable([[1,2],[3,4]])

In [8]:
tenser

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [9]:
tenser.numpy()

array([[1, 2],
       [3, 4]], dtype=int32)

In [10]:
tenser1 = tf.constant([[1,2],[3,4]])

In [12]:
(tenser1+2).numpy()

array([[3, 4],
       [5, 6]], dtype=int32)

In [13]:
(tenser1*2).numpy()

array([[2, 4],
       [6, 8]], dtype=int32)

In [14]:
import numpy as np  

In [15]:
np.square(tenser1)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)