In [69]:
#Missing Data

In [70]:
import numpy as np 
import pandas as pd 


In [71]:
df = pd.DataFrame({'A':[1, 2, np.nan ],
                   'B':[5,  np.nan, np.nan ],
                   'C':[1, 2, 3] }) 

In [72]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [73]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [74]:
df.dropna(subset=['A'])

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [75]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [76]:
df.dropna(axis=1) 

C
0  1
1  2
2  3

In [77]:
df.drop('A',axis=1)

B  C
0  5.0  1
1  NaN  2
2  NaN  3

In [78]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [79]:
df.fillna(value=0)

A    B  C
0  1.0  5.0  1
1  2.0  0.0  2
2  0.0  0.0  3

In [80]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [81]:
mean = df['A'].mean()

In [82]:
mean

1.5

In [83]:
df['A'].fillna(mean, inplace= True)

In [84]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  1.5  NaN  3

In [85]:
df = pd.DataFrame({'A':[1, 2, np.nan],
                    'B':[5, np.nan, np.nan],
                    'C':[1, 2, 3]})

In [86]:
df['A'].fillna(df['A'].mean(), inplace= True)

In [87]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  1.5  NaN  3

In [88]:
df = pd.DataFrame({'A':[1, 2, np.nan],
                    'B':[5, np.nan, np.nan],
                    'C':[1, 2, 3]})
df                  

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [89]:
for feature in ['A','B']:
    df[feature].fillna(df[feature].mean(), inplace = True)
df

A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  1.5  5.0  3

In [90]:
df = pd.DataFrame({'A':['$1,000', '$2,000', np.nan],
                    'B':[5, np.nan, np.nan],
                    'C':[1, 2, 3]})
df

A    B  C
0  $1,000  5.0  1
1  $2,000  NaN  2
2     NaN  NaN  3

In [91]:
for feature in ['B']:
    df[feature].fillna(df[feature].mean(), inplace= True)
for feature in ['A']:
    df[feature] = df[feature].map(lambda x:x.replace('$','').replace(',',''), na_action= 'ignore')
    df[feature] = df[feature].astype(float)
    df[feature].fillna(df[feature].mean(), inplace= True)
df

A    B  C
0  1000.0  5.0  1
1  2000.0  5.0  2
2  1500.0  5.0  3

In [92]:
df = pd.DataFrame({'A':[1, 2, np.nan],
                    'B':[5, np.nan, np.nan],
                    'C':[1, 2, 3],
                    'D':['A','B','C']})
df                  

A    B  C  D
0  1.0  5.0  1  A
1  2.0  NaN  2  B
2  NaN  NaN  3  C

In [93]:
from sklearn.impute import SimpleImputer 
imputer = SimpleImputer( strategy='mean')

In [94]:
df_num = df.drop('D', axis=1)

In [95]:
df_num

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [96]:
imputer.fit(df_num) #fit คือการคำนวน ยังไม่แทนค่า

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='mean', verbose=0)

In [97]:
imputer.statistics_

array([1.5, 5. , 2. ])

In [98]:
df_num.mean().values #เทียบกับ imputer

array([1.5, 5. , 2. ])

In [99]:
x = imputer.transform(df_num)

In [100]:
x # output numpy array

array([[1. , 5. , 1. ],
       [2. , 5. , 2. ],
       [1.5, 5. , 3. ]])

In [101]:
df_tr = pd.DataFrame(x, columns=df_num.columns) #แปลง array เป็น Dataframe

In [102]:
df_tr

A    B    C
0  1.0  5.0  1.0
1  2.0  5.0  2.0
2  1.5  5.0  3.0

In [103]:
df_tr = pd.concat([df_tr, df['D']],axis=1)

In [104]:
df_tr

A    B    C  D
0  1.0  5.0  1.0  A
1  2.0  5.0  2.0  B
2  1.5  5.0  3.0  C

In [105]:
df = pd.DataFrame({'A':[1, 2, np.nan],
                    'B':[5, np.nan, np.nan],
                    'C':[1, 2, 3],
                    'D':['A','B','C']})
df    

A    B  C  D
0  1.0  5.0  1  A
1  2.0  NaN  2  B
2  NaN  NaN  3  C

In [106]:
from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(strategy='mean')

In [107]:
df_num = df.drop('D', axis=1)

In [113]:
df_tr = pd.DataFrame(imputer.fit_transform(df_num), columns = df_num.columns)
df_tr

A    B    C
0  1.0  5.0  1.0
1  2.0  5.0  2.0
2  1.5  5.0  3.0

In [114]:
df_tr = pd.concat([df_tr,df['D']], axis=1)
df_tr

A    B    C  D
0  1.0  5.0  1.0  A
1  2.0  5.0  2.0  B
2  1.5  5.0  3.0  C